//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ppt.status;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.trainwatch.nre.darwin.model.ppt.status package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PPConnect_QNAME = new QName("http://thalesgroup.com/RTTI/PushPortStatus/root_1", "PPConnect");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.trainwatch.nre.darwin.model.ppt.status
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PPStatus }
     * 
     */
    public PPStatus createPPStatus() {
        return new PPStatus();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link PPReqVersion }
     * 
     */
    public PPReqVersion createPPReqVersion() {
        return new PPReqVersion();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://thalesgroup.com/RTTI/PushPortStatus/root_1", name = "PPConnect")
    public JAXBElement<Object> createPPConnect(Object value) {
        return new JAXBElement<Object>(_PPConnect_QNAME, Object.class, null, value);
    }

}
