#!/bin/bash
#
# Run's the utility application
#
# Now this is messy & needs doing right later, but it gets around a problem
# with using "java -jar" and java.util.ServiceLoader. When used with -jar
# ServiceLoader only loads the Utility's in the first jar one is found
# not all of them, but when run with "-cp" it works.
#
DIR=$(dirname $0)
CP=$(echo $(ls $DIR/*.jar)|sed "s/ /:/g");
exec java -cp $CP uk.trainwatch.app.util.Main $@
