//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ppt.forecasts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Platform number with associated flags
 * 
 * <p>Java class for PlatformData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlatformData">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1>PlatformType">
 *       &lt;attribute name="platsup" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="cisPlatsup" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="platsrc" default="P">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;length value="1"/>
 *             &lt;enumeration value="P"/>
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="M"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="conf" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlatformData", propOrder = {
    "value"
})
public class PlatformData {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "platsup")
    protected Boolean platsup;
    @XmlAttribute(name = "cisPlatsup")
    protected Boolean cisPlatsup;
    @XmlAttribute(name = "platsrc")
    protected String platsrc;
    @XmlAttribute(name = "conf")
    protected Boolean conf;

    /**
     * Defines a platform number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    public boolean isSetValue() {
        return (this.value!= null);
    }

    /**
     * Gets the value of the platsup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getPlatsup() {
        if (platsup == null) {
            return false;
        } else {
            return platsup;
        }
    }

    /**
     * Sets the value of the platsup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlatsup(boolean value) {
        this.platsup = value;
    }

    public boolean isSetPlatsup() {
        return (this.platsup!= null);
    }

    public void unsetPlatsup() {
        this.platsup = null;
    }

    /**
     * Gets the value of the cisPlatsup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getCisPlatsup() {
        if (cisPlatsup == null) {
            return false;
        } else {
            return cisPlatsup;
        }
    }

    /**
     * Sets the value of the cisPlatsup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCisPlatsup(boolean value) {
        this.cisPlatsup = value;
    }

    public boolean isSetCisPlatsup() {
        return (this.cisPlatsup!= null);
    }

    public void unsetCisPlatsup() {
        this.cisPlatsup = null;
    }

    /**
     * Gets the value of the platsrc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatsrc() {
        if (platsrc == null) {
            return "P";
        } else {
            return platsrc;
        }
    }

    /**
     * Sets the value of the platsrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatsrc(String value) {
        this.platsrc = value;
    }

    public boolean isSetPlatsrc() {
        return (this.platsrc!= null);
    }

    /**
     * Gets the value of the conf property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getConf() {
        if (conf == null) {
            return false;
        } else {
            return conf;
        }
    }

    /**
     * Sets the value of the conf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConf(boolean value) {
        this.conf = value;
    }

    public boolean isSetConf() {
        return (this.conf!= null);
    }

    public void unsetConf() {
        this.conf = null;
    }

}
