//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ppt.forecasts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Type describing time-based forecast attributes for a TS arrival/departure/pass
 * 
 * <p>Java class for TSTimeData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TSTimeData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="et" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}RTTITimeType" />
 *       &lt;attribute name="wet" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}RTTITimeType" />
 *       &lt;attribute name="at" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}RTTITimeType" />
 *       &lt;attribute name="atRemoved" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="etmin" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}RTTITimeType" />
 *       &lt;attribute name="etUnknown" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="delayed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="srcInst" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}SourceTypeInst" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TSTimeData")
public class TSTimeData {

    @XmlAttribute(name = "et")
    protected String et;
    @XmlAttribute(name = "wet")
    protected String wet;
    @XmlAttribute(name = "at")
    protected String at;
    @XmlAttribute(name = "atRemoved")
    protected Boolean atRemoved;
    @XmlAttribute(name = "etmin")
    protected String etmin;
    @XmlAttribute(name = "etUnknown")
    protected Boolean etUnknown;
    @XmlAttribute(name = "delayed")
    protected Boolean delayed;
    @XmlAttribute(name = "src")
    protected String src;
    @XmlAttribute(name = "srcInst")
    protected String srcInst;

    /**
     * Gets the value of the et property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEt() {
        return et;
    }

    /**
     * Sets the value of the et property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEt(String value) {
        this.et = value;
    }

    public boolean isSetEt() {
        return (this.et!= null);
    }

    /**
     * Gets the value of the wet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWet() {
        return wet;
    }

    /**
     * Sets the value of the wet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWet(String value) {
        this.wet = value;
    }

    public boolean isSetWet() {
        return (this.wet!= null);
    }

    /**
     * Gets the value of the at property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAt() {
        return at;
    }

    /**
     * Sets the value of the at property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAt(String value) {
        this.at = value;
    }

    public boolean isSetAt() {
        return (this.at!= null);
    }

    /**
     * Gets the value of the atRemoved property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getAtRemoved() {
        if (atRemoved == null) {
            return false;
        } else {
            return atRemoved;
        }
    }

    /**
     * Sets the value of the atRemoved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAtRemoved(boolean value) {
        this.atRemoved = value;
    }

    public boolean isSetAtRemoved() {
        return (this.atRemoved!= null);
    }

    public void unsetAtRemoved() {
        this.atRemoved = null;
    }

    /**
     * Gets the value of the etmin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEtmin() {
        return etmin;
    }

    /**
     * Sets the value of the etmin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEtmin(String value) {
        this.etmin = value;
    }

    public boolean isSetEtmin() {
        return (this.etmin!= null);
    }

    /**
     * Gets the value of the etUnknown property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getEtUnknown() {
        if (etUnknown == null) {
            return false;
        } else {
            return etUnknown;
        }
    }

    /**
     * Sets the value of the etUnknown property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEtUnknown(boolean value) {
        this.etUnknown = value;
    }

    public boolean isSetEtUnknown() {
        return (this.etUnknown!= null);
    }

    public void unsetEtUnknown() {
        this.etUnknown = null;
    }

    /**
     * Gets the value of the delayed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getDelayed() {
        if (delayed == null) {
            return false;
        } else {
            return delayed;
        }
    }

    /**
     * Sets the value of the delayed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDelayed(boolean value) {
        this.delayed = value;
    }

    public boolean isSetDelayed() {
        return (this.delayed!= null);
    }

    public void unsetDelayed() {
        this.delayed = null;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrc(String value) {
        this.src = value;
    }

    public boolean isSetSrc() {
        return (this.src!= null);
    }

    /**
     * Gets the value of the srcInst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcInst() {
        return srcInst;
    }

    /**
     * Sets the value of the srcInst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcInst(String value) {
        this.srcInst = value;
    }

    public boolean isSetSrcInst() {
        return (this.srcInst!= null);
    }

}
