//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ctt.referenceschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="tpl" use="required" type="{http://www.thalesgroup.com/rtti/XmlRefData/v3}TiplocType" />
 *       &lt;attribute name="crs" type="{http://www.thalesgroup.com/rtti/XmlRefData/v3}CrsType" />
 *       &lt;attribute name="toc" type="{http://www.thalesgroup.com/rtti/XmlRefData/v3}TOCType" />
 *       &lt;attribute name="locname" use="required" type="{http://www.thalesgroup.com/rtti/XmlRefData/v3}LocationNameType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "LocationRef")
public class LocationRef {

    @XmlAttribute(name = "tpl", required = true)
    protected String tpl;
    @XmlAttribute(name = "crs")
    protected String crs;
    @XmlAttribute(name = "toc")
    protected String toc;
    @XmlAttribute(name = "locname", required = true)
    protected String locname;

    /**
     * Gets the value of the tpl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpl() {
        return tpl;
    }

    /**
     * Sets the value of the tpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpl(String value) {
        this.tpl = value;
    }

    public boolean isSetTpl() {
        return (this.tpl!= null);
    }

    /**
     * Gets the value of the crs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrs() {
        return crs;
    }

    /**
     * Sets the value of the crs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrs(String value) {
        this.crs = value;
    }

    public boolean isSetCrs() {
        return (this.crs!= null);
    }

    /**
     * Gets the value of the toc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToc() {
        return toc;
    }

    /**
     * Sets the value of the toc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToc(String value) {
        this.toc = value;
    }

    public boolean isSetToc() {
        return (this.toc!= null);
    }

    /**
     * Gets the value of the locname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocname() {
        return locname;
    }

    /**
     * Sets the value of the locname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocname(String value) {
        this.locname = value;
    }

    public boolean isSetLocname() {
        return (this.locname!= null);
    }

}
