//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ctt.referenceschema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.trainwatch.nre.darwin.model.ctt.referenceschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.trainwatch.nre.darwin.model.ctt.referenceschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PportTimetableRef }
     * 
     */
    public PportTimetableRef createPportTimetableRef() {
        return new PportTimetableRef();
    }

    /**
     * Create an instance of {@link CISSource }
     * 
     */
    public CISSource createCISSource() {
        return new CISSource();
    }

    /**
     * Create an instance of {@link LocationRef }
     * 
     */
    public LocationRef createLocationRef() {
        return new LocationRef();
    }

    /**
     * Create an instance of {@link TocRef }
     * 
     */
    public TocRef createTocRef() {
        return new TocRef();
    }

    /**
     * Create an instance of {@link PportTimetableRef.LateRunningReasons }
     * 
     */
    public PportTimetableRef.LateRunningReasons createPportTimetableRefLateRunningReasons() {
        return new PportTimetableRef.LateRunningReasons();
    }

    /**
     * Create an instance of {@link PportTimetableRef.CancellationReasons }
     * 
     */
    public PportTimetableRef.CancellationReasons createPportTimetableRefCancellationReasons() {
        return new PportTimetableRef.CancellationReasons();
    }

    /**
     * Create an instance of {@link Via }
     * 
     */
    public Via createVia() {
        return new Via();
    }

    /**
     * Create an instance of {@link Reason }
     * 
     */
    public Reason createReason() {
        return new Reason();
    }

}
