//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.thalesgroup.com/rtti/PushPort/v12", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.trainwatch.nre.darwin.model.ppt.schema;
