//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ppt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;
import uk.trainwatch.nre.darwin.model.ppt.status.StatusType;
import uk.trainwatch.nre.darwin.model.util.PportUtil;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="QueryTimetable" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="TimeTableId">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1>TimetableIDType">
 *                 &lt;attribute name="ttfile" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}TimetableFilenameType" />
 *                 &lt;attribute name="ttreffile" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}TimetableFilenameType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GetSnapshotReq">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="viaftp" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GetFullSnapshotReq">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="viaftp" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SnapshotId" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}SnapshotIDType"/>
 *         &lt;element name="StartUpdateReq" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="StopUpdateReq" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="FailureResp">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://thalesgroup.com/RTTI/PushPortStatus/root_1>StatusType">
 *                 &lt;attribute name="requestSource" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}SourceTypeInst" />
 *                 &lt;attribute name="requestID" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}DCISRequestID" />
 *                 &lt;anyAttribute processContents='lax'/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="uR">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.thalesgroup.com/rtti/PushPort/v12}DataResponse">
 *                 &lt;attribute name="updateOrigin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="requestSource" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}SourceTypeInst" />
 *                 &lt;attribute name="requestID" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}DCISRequestID" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sR" type="{http://www.thalesgroup.com/rtti/PushPort/v12}DataResponse"/>
 *       &lt;/choice>
 *       &lt;attribute name="ts" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}RTTIDateTimeType" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryTimetable",
    "timeTableId",
    "getSnapshotReq",
    "getFullSnapshotReq",
    "snapshotId",
    "startUpdateReq",
    "stopUpdateReq",
    "failureResp",
    "ur",
    "sr"
})
@XmlRootElement(name = "Pport")
public class Pport
    implements PportUtil
{

    @XmlElement(name = "QueryTimetable")
    protected Object queryTimetable;
    @XmlElement(name = "TimeTableId")
    protected Pport.TimeTableId timeTableId;
    @XmlElement(name = "GetSnapshotReq")
    protected Pport.GetSnapshotReq getSnapshotReq;
    @XmlElement(name = "GetFullSnapshotReq")
    protected Pport.GetFullSnapshotReq getFullSnapshotReq;
    @XmlElement(name = "SnapshotId")
    protected String snapshotId;
    @XmlElement(name = "StartUpdateReq")
    protected Object startUpdateReq;
    @XmlElement(name = "StopUpdateReq")
    protected Object stopUpdateReq;
    @XmlElement(name = "FailureResp")
    protected Pport.FailureResp failureResp;
    @XmlElement(name = "uR")
    protected Pport.UR ur;
    @XmlElement(name = "sR")
    protected DataResponse sr;
    @XmlAttribute(name = "ts", required = true)
    protected XMLGregorianCalendar ts;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the queryTimetable property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getQueryTimetable() {
        return queryTimetable;
    }

    /**
     * Sets the value of the queryTimetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setQueryTimetable(Object value) {
        this.queryTimetable = value;
    }

    public boolean isSetQueryTimetable() {
        return (this.queryTimetable!= null);
    }

    /**
     * Gets the value of the timeTableId property.
     * 
     * @return
     *     possible object is
     *     {@link Pport.TimeTableId }
     *     
     */
    public Pport.TimeTableId getTimeTableId() {
        return timeTableId;
    }

    /**
     * Sets the value of the timeTableId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pport.TimeTableId }
     *     
     */
    public void setTimeTableId(Pport.TimeTableId value) {
        this.timeTableId = value;
    }

    public boolean isSetTimeTableId() {
        return (this.timeTableId!= null);
    }

    /**
     * Gets the value of the getSnapshotReq property.
     * 
     * @return
     *     possible object is
     *     {@link Pport.GetSnapshotReq }
     *     
     */
    public Pport.GetSnapshotReq getGetSnapshotReq() {
        return getSnapshotReq;
    }

    /**
     * Sets the value of the getSnapshotReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pport.GetSnapshotReq }
     *     
     */
    public void setGetSnapshotReq(Pport.GetSnapshotReq value) {
        this.getSnapshotReq = value;
    }

    public boolean isSetGetSnapshotReq() {
        return (this.getSnapshotReq!= null);
    }

    /**
     * Gets the value of the getFullSnapshotReq property.
     * 
     * @return
     *     possible object is
     *     {@link Pport.GetFullSnapshotReq }
     *     
     */
    public Pport.GetFullSnapshotReq getGetFullSnapshotReq() {
        return getFullSnapshotReq;
    }

    /**
     * Sets the value of the getFullSnapshotReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pport.GetFullSnapshotReq }
     *     
     */
    public void setGetFullSnapshotReq(Pport.GetFullSnapshotReq value) {
        this.getFullSnapshotReq = value;
    }

    public boolean isSetGetFullSnapshotReq() {
        return (this.getFullSnapshotReq!= null);
    }

    /**
     * Gets the value of the snapshotId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnapshotId() {
        return snapshotId;
    }

    /**
     * Sets the value of the snapshotId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnapshotId(String value) {
        this.snapshotId = value;
    }

    public boolean isSetSnapshotId() {
        return (this.snapshotId!= null);
    }

    /**
     * Gets the value of the startUpdateReq property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStartUpdateReq() {
        return startUpdateReq;
    }

    /**
     * Sets the value of the startUpdateReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStartUpdateReq(Object value) {
        this.startUpdateReq = value;
    }

    public boolean isSetStartUpdateReq() {
        return (this.startUpdateReq!= null);
    }

    /**
     * Gets the value of the stopUpdateReq property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStopUpdateReq() {
        return stopUpdateReq;
    }

    /**
     * Sets the value of the stopUpdateReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStopUpdateReq(Object value) {
        this.stopUpdateReq = value;
    }

    public boolean isSetStopUpdateReq() {
        return (this.stopUpdateReq!= null);
    }

    /**
     * Gets the value of the failureResp property.
     * 
     * @return
     *     possible object is
     *     {@link Pport.FailureResp }
     *     
     */
    public Pport.FailureResp getFailureResp() {
        return failureResp;
    }

    /**
     * Sets the value of the failureResp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pport.FailureResp }
     *     
     */
    public void setFailureResp(Pport.FailureResp value) {
        this.failureResp = value;
    }

    public boolean isSetFailureResp() {
        return (this.failureResp!= null);
    }

    /**
     * Gets the value of the ur property.
     * 
     * @return
     *     possible object is
     *     {@link Pport.UR }
     *     
     */
    public Pport.UR getUR() {
        return ur;
    }

    /**
     * Sets the value of the ur property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pport.UR }
     *     
     */
    public void setUR(Pport.UR value) {
        this.ur = value;
    }

    public boolean isSetUR() {
        return (this.ur!= null);
    }

    /**
     * Gets the value of the sr property.
     * 
     * @return
     *     possible object is
     *     {@link DataResponse }
     *     
     */
    public DataResponse getSR() {
        return sr;
    }

    /**
     * Sets the value of the sr property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataResponse }
     *     
     */
    public void setSR(DataResponse value) {
        this.sr = value;
    }

    public boolean isSetSR() {
        return (this.sr!= null);
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTs(XMLGregorianCalendar value) {
        this.ts = value;
    }

    public boolean isSetTs() {
        return (this.ts!= null);
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.version!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://thalesgroup.com/RTTI/PushPortStatus/root_1>StatusType">
     *       &lt;attribute name="requestSource" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}SourceTypeInst" />
     *       &lt;attribute name="requestID" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}DCISRequestID" />
     *       &lt;anyAttribute processContents='lax'/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FailureResp
        extends StatusType
    {

        @XmlAttribute(name = "requestSource")
        protected String requestSource;
        @XmlAttribute(name = "requestID")
        protected String requestID;

        /**
         * Gets the value of the requestSource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestSource() {
            return requestSource;
        }

        /**
         * Sets the value of the requestSource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestSource(String value) {
            this.requestSource = value;
        }

        public boolean isSetRequestSource() {
            return (this.requestSource!= null);
        }

        /**
         * Gets the value of the requestID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestID() {
            return requestID;
        }

        /**
         * Sets the value of the requestID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestID(String value) {
            this.requestID = value;
        }

        public boolean isSetRequestID() {
            return (this.requestID!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="viaftp" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class GetFullSnapshotReq {

        @XmlAttribute(name = "viaftp")
        protected Boolean viaftp;

        /**
         * Gets the value of the viaftp property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean getViaftp() {
            if (viaftp == null) {
                return false;
            } else {
                return viaftp;
            }
        }

        /**
         * Sets the value of the viaftp property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setViaftp(boolean value) {
            this.viaftp = value;
        }

        public boolean isSetViaftp() {
            return (this.viaftp!= null);
        }

        public void unsetViaftp() {
            this.viaftp = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="viaftp" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class GetSnapshotReq {

        @XmlAttribute(name = "viaftp")
        protected Boolean viaftp;

        /**
         * Gets the value of the viaftp property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean getViaftp() {
            if (viaftp == null) {
                return false;
            } else {
                return viaftp;
            }
        }

        /**
         * Sets the value of the viaftp property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setViaftp(boolean value) {
            this.viaftp = value;
        }

        public boolean isSetViaftp() {
            return (this.viaftp!= null);
        }

        public void unsetViaftp() {
            this.viaftp = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1>TimetableIDType">
     *       &lt;attribute name="ttfile" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}TimetableFilenameType" />
     *       &lt;attribute name="ttreffile" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}TimetableFilenameType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TimeTableId {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "ttfile", required = true)
        protected String ttfile;
        @XmlAttribute(name = "ttreffile", required = true)
        protected String ttreffile;

        /**
         * Unique Timetable identifier 
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        public boolean isSetValue() {
            return (this.value!= null);
        }

        /**
         * Gets the value of the ttfile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTtfile() {
            return ttfile;
        }

        /**
         * Sets the value of the ttfile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTtfile(String value) {
            this.ttfile = value;
        }

        public boolean isSetTtfile() {
            return (this.ttfile!= null);
        }

        /**
         * Gets the value of the ttreffile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTtreffile() {
            return ttreffile;
        }

        /**
         * Sets the value of the ttreffile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTtreffile(String value) {
            this.ttreffile = value;
        }

        public boolean isSetTtreffile() {
            return (this.ttreffile!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.thalesgroup.com/rtti/PushPort/v12}DataResponse">
     *       &lt;attribute name="updateOrigin" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="requestSource" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}SourceTypeInst" />
     *       &lt;attribute name="requestID" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}DCISRequestID" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UR
        extends DataResponse
    {

        @XmlAttribute(name = "updateOrigin")
        protected String updateOrigin;
        @XmlAttribute(name = "requestSource")
        protected String requestSource;
        @XmlAttribute(name = "requestID")
        protected String requestID;

        /**
         * Gets the value of the updateOrigin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUpdateOrigin() {
            return updateOrigin;
        }

        /**
         * Sets the value of the updateOrigin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUpdateOrigin(String value) {
            this.updateOrigin = value;
        }

        public boolean isSetUpdateOrigin() {
            return (this.updateOrigin!= null);
        }

        /**
         * Gets the value of the requestSource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestSource() {
            return requestSource;
        }

        /**
         * Sets the value of the requestSource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestSource(String value) {
            this.requestSource = value;
        }

        public boolean isSetRequestSource() {
            return (this.requestSource!= null);
        }

        /**
         * Gets the value of the requestID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestID() {
            return requestID;
        }

        /**
         * Sets the value of the requestID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestID(String value) {
            this.requestID = value;
        }

        public boolean isSetRequestID() {
            return (this.requestID!= null);
        }

    }

}
