//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ppt.trainalerts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A list of services to which the alert applies
 * 
 * <p>Java class for AlertServices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlertServices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AlertService" type="{http://www.thalesgroup.com/rtti/PushPort/TrainAlerts/v1}AlertService" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlertServices", propOrder = {
    "alertService"
})
public class AlertServices {

    @XmlElement(name = "AlertService")
    protected List<AlertService> alertService;

    /**
     * Gets the value of the alertService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alertService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlertService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlertService }
     * 
     * 
     */
    public List<AlertService> getAlertService() {
        if (alertService == null) {
            alertService = new ArrayList<AlertService>();
        }
        return this.alertService;
    }

    public boolean isSetAlertService() {
        return ((this.alertService!= null)&&(!this.alertService.isEmpty()));
    }

    public void unsetAlertService() {
        this.alertService = null;
    }

}
