//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ppt.trainalerts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Train Alert
 * 
 * <p>Java class for TrainAlert complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainAlert">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AlertID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AlertServices" type="{http://www.thalesgroup.com/rtti/PushPort/TrainAlerts/v1}AlertServices"/>
 *         &lt;element name="SendAlertBySMS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="SendAlertByEmail" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="SendAlertByTwitter" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AlertText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Audience" type="{http://www.thalesgroup.com/rtti/PushPort/TrainAlerts/v1}AlertAudienceType"/>
 *         &lt;element name="AlertType" type="{http://www.thalesgroup.com/rtti/PushPort/TrainAlerts/v1}AlertType"/>
 *         &lt;element name="CopiedFromAlertID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CopiedFromSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainAlert", propOrder = {
    "alertID",
    "alertServices",
    "sendAlertBySMS",
    "sendAlertByEmail",
    "sendAlertByTwitter",
    "source",
    "alertText",
    "audience",
    "alertType",
    "copiedFromAlertID",
    "copiedFromSource"
})
public class TrainAlert {

    @XmlElement(name = "AlertID", required = true)
    protected String alertID;
    @XmlElement(name = "AlertServices", required = true)
    protected AlertServices alertServices;
    @XmlElement(name = "SendAlertBySMS")
    protected boolean sendAlertBySMS;
    @XmlElement(name = "SendAlertByEmail")
    protected boolean sendAlertByEmail;
    @XmlElement(name = "SendAlertByTwitter")
    protected boolean sendAlertByTwitter;
    @XmlElement(name = "Source", required = true)
    protected String source;
    @XmlElement(name = "AlertText", required = true)
    protected String alertText;
    @XmlElement(name = "Audience", required = true)
    protected AlertAudienceType audience;
    @XmlElement(name = "AlertType", required = true)
    protected AlertType alertType;
    @XmlElement(name = "CopiedFromAlertID")
    protected String copiedFromAlertID;
    @XmlElement(name = "CopiedFromSource")
    protected String copiedFromSource;

    /**
     * Gets the value of the alertID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertID() {
        return alertID;
    }

    /**
     * Sets the value of the alertID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertID(String value) {
        this.alertID = value;
    }

    public boolean isSetAlertID() {
        return (this.alertID!= null);
    }

    /**
     * Gets the value of the alertServices property.
     * 
     * @return
     *     possible object is
     *     {@link AlertServices }
     *     
     */
    public AlertServices getAlertServices() {
        return alertServices;
    }

    /**
     * Sets the value of the alertServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertServices }
     *     
     */
    public void setAlertServices(AlertServices value) {
        this.alertServices = value;
    }

    public boolean isSetAlertServices() {
        return (this.alertServices!= null);
    }

    /**
     * Gets the value of the sendAlertBySMS property.
     * 
     */
    public boolean isSendAlertBySMS() {
        return sendAlertBySMS;
    }

    /**
     * Sets the value of the sendAlertBySMS property.
     * 
     */
    public void setSendAlertBySMS(boolean value) {
        this.sendAlertBySMS = value;
    }

    public boolean isSetSendAlertBySMS() {
        return true;
    }

    /**
     * Gets the value of the sendAlertByEmail property.
     * 
     */
    public boolean isSendAlertByEmail() {
        return sendAlertByEmail;
    }

    /**
     * Sets the value of the sendAlertByEmail property.
     * 
     */
    public void setSendAlertByEmail(boolean value) {
        this.sendAlertByEmail = value;
    }

    public boolean isSetSendAlertByEmail() {
        return true;
    }

    /**
     * Gets the value of the sendAlertByTwitter property.
     * 
     */
    public boolean isSendAlertByTwitter() {
        return sendAlertByTwitter;
    }

    /**
     * Sets the value of the sendAlertByTwitter property.
     * 
     */
    public void setSendAlertByTwitter(boolean value) {
        this.sendAlertByTwitter = value;
    }

    public boolean isSetSendAlertByTwitter() {
        return true;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    public boolean isSetSource() {
        return (this.source!= null);
    }

    /**
     * Gets the value of the alertText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertText() {
        return alertText;
    }

    /**
     * Sets the value of the alertText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertText(String value) {
        this.alertText = value;
    }

    public boolean isSetAlertText() {
        return (this.alertText!= null);
    }

    /**
     * Gets the value of the audience property.
     * 
     * @return
     *     possible object is
     *     {@link AlertAudienceType }
     *     
     */
    public AlertAudienceType getAudience() {
        return audience;
    }

    /**
     * Sets the value of the audience property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertAudienceType }
     *     
     */
    public void setAudience(AlertAudienceType value) {
        this.audience = value;
    }

    public boolean isSetAudience() {
        return (this.audience!= null);
    }

    /**
     * Gets the value of the alertType property.
     * 
     * @return
     *     possible object is
     *     {@link AlertType }
     *     
     */
    public AlertType getAlertType() {
        return alertType;
    }

    /**
     * Sets the value of the alertType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertType }
     *     
     */
    public void setAlertType(AlertType value) {
        this.alertType = value;
    }

    public boolean isSetAlertType() {
        return (this.alertType!= null);
    }

    /**
     * Gets the value of the copiedFromAlertID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopiedFromAlertID() {
        return copiedFromAlertID;
    }

    /**
     * Sets the value of the copiedFromAlertID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopiedFromAlertID(String value) {
        this.copiedFromAlertID = value;
    }

    public boolean isSetCopiedFromAlertID() {
        return (this.copiedFromAlertID!= null);
    }

    /**
     * Gets the value of the copiedFromSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopiedFromSource() {
        return copiedFromSource;
    }

    /**
     * Sets the value of the copiedFromSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopiedFromSource(String value) {
        this.copiedFromSource = value;
    }

    public boolean isSetCopiedFromSource() {
        return (this.copiedFromSource!= null);
    }

}
