//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ctt.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.trainwatch.nre.darwin.model.ctt.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.trainwatch.nre.darwin.model.ctt.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PportTimetable }
     * 
     */
    public PportTimetable createPportTimetable() {
        return new PportTimetable();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link PP }
     * 
     */
    public PP createPP() {
        return new PP();
    }

    /**
     * Create an instance of {@link DT }
     * 
     */
    public DT createDT() {
        return new DT();
    }

    /**
     * Create an instance of {@link AssocService }
     * 
     */
    public AssocService createAssocService() {
        return new AssocService();
    }

    /**
     * Create an instance of {@link OPOR }
     * 
     */
    public OPOR createOPOR() {
        return new OPOR();
    }

    /**
     * Create an instance of {@link OR }
     * 
     */
    public OR createOR() {
        return new OR();
    }

    /**
     * Create an instance of {@link OPDT }
     * 
     */
    public OPDT createOPDT() {
        return new OPDT();
    }

    /**
     * Create an instance of {@link IP }
     * 
     */
    public IP createIP() {
        return new IP();
    }

    /**
     * Create an instance of {@link OPIP }
     * 
     */
    public OPIP createOPIP() {
        return new OPIP();
    }

}
