//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ctt.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import uk.trainwatch.nre.darwin.model.ppt.commontypes.DisruptionReasonType;


/**
 * Train Schedule
 * 
 * <p>Java class for Schedule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Schedule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="2">
 *           &lt;element name="OR" type="{http://www.thalesgroup.com/rtti/XmlTimetable/v8}OR"/>
 *           &lt;element name="OPOR" type="{http://www.thalesgroup.com/rtti/XmlTimetable/v8}OPOR"/>
 *           &lt;element name="IP" type="{http://www.thalesgroup.com/rtti/XmlTimetable/v8}IP"/>
 *           &lt;element name="OPIP" type="{http://www.thalesgroup.com/rtti/XmlTimetable/v8}OPIP"/>
 *           &lt;element name="PP" type="{http://www.thalesgroup.com/rtti/XmlTimetable/v8}PP"/>
 *           &lt;element name="DT" type="{http://www.thalesgroup.com/rtti/XmlTimetable/v8}DT"/>
 *           &lt;element name="OPDT" type="{http://www.thalesgroup.com/rtti/XmlTimetable/v8}OPDT"/>
 *         &lt;/choice>
 *         &lt;element name="cancelReason" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}DisruptionReasonType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rid" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}RIDType" />
 *       &lt;attribute name="uid" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}UIDType" />
 *       &lt;attribute name="trainId" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}TrainIdType" />
 *       &lt;attribute name="ssd" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}RTTIDateType" />
 *       &lt;attribute name="toc" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}TOCType" />
 *       &lt;attribute name="status" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}CIFTrainStatusType" default="P" />
 *       &lt;attribute name="trainCat" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}CIFTrainCategoryType" default="OO" />
 *       &lt;attribute name="isPassengerSvc" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="isCharter" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="qtrain" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="can" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Schedule", propOrder = {
    "orOrOPOROrIP",
    "cancelReason"
})
public class Schedule {

    @XmlElements({
        @XmlElement(name = "OR", type = OR.class),
        @XmlElement(name = "OPOR", type = OPOR.class),
        @XmlElement(name = "IP", type = IP.class),
        @XmlElement(name = "OPIP", type = OPIP.class),
        @XmlElement(name = "PP", type = PP.class),
        @XmlElement(name = "DT", type = DT.class),
        @XmlElement(name = "OPDT", type = OPDT.class)
    })
    protected List<Object> orOrOPOROrIP;
    protected DisruptionReasonType cancelReason;
    @XmlAttribute(name = "rid", required = true)
    protected String rid;
    @XmlAttribute(name = "uid", required = true)
    protected String uid;
    @XmlAttribute(name = "trainId", required = true)
    protected String trainId;
    @XmlAttribute(name = "ssd", required = true)
    protected XMLGregorianCalendar ssd;
    @XmlAttribute(name = "toc", required = true)
    protected String toc;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "trainCat")
    protected String trainCat;
    @XmlAttribute(name = "isPassengerSvc")
    protected Boolean isPassengerSvc;
    @XmlAttribute(name = "deleted")
    protected Boolean deleted;
    @XmlAttribute(name = "isCharter")
    protected Boolean isCharter;
    @XmlAttribute(name = "qtrain")
    protected Boolean qtrain;
    @XmlAttribute(name = "can")
    protected Boolean can;

    /**
     * Gets the value of the orOrOPOROrIP property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orOrOPOROrIP property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOROrOPOROrIP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OR }
     * {@link OPOR }
     * {@link IP }
     * {@link OPIP }
     * {@link PP }
     * {@link DT }
     * {@link OPDT }
     * 
     * 
     */
    public List<Object> getOROrOPOROrIP() {
        if (orOrOPOROrIP == null) {
            orOrOPOROrIP = new ArrayList<Object>();
        }
        return this.orOrOPOROrIP;
    }

    public boolean isSetOROrOPOROrIP() {
        return ((this.orOrOPOROrIP!= null)&&(!this.orOrOPOROrIP.isEmpty()));
    }

    public void unsetOROrOPOROrIP() {
        this.orOrOPOROrIP = null;
    }

    /**
     * Gets the value of the cancelReason property.
     * 
     * @return
     *     possible object is
     *     {@link DisruptionReasonType }
     *     
     */
    public DisruptionReasonType getCancelReason() {
        return cancelReason;
    }

    /**
     * Sets the value of the cancelReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisruptionReasonType }
     *     
     */
    public void setCancelReason(DisruptionReasonType value) {
        this.cancelReason = value;
    }

    public boolean isSetCancelReason() {
        return (this.cancelReason!= null);
    }

    /**
     * Gets the value of the rid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRid() {
        return rid;
    }

    /**
     * Sets the value of the rid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRid(String value) {
        this.rid = value;
    }

    public boolean isSetRid() {
        return (this.rid!= null);
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

    public boolean isSetUid() {
        return (this.uid!= null);
    }

    /**
     * Gets the value of the trainId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainId() {
        return trainId;
    }

    /**
     * Sets the value of the trainId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainId(String value) {
        this.trainId = value;
    }

    public boolean isSetTrainId() {
        return (this.trainId!= null);
    }

    /**
     * Gets the value of the ssd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSsd() {
        return ssd;
    }

    /**
     * Sets the value of the ssd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSsd(XMLGregorianCalendar value) {
        this.ssd = value;
    }

    public boolean isSetSsd() {
        return (this.ssd!= null);
    }

    /**
     * Gets the value of the toc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToc() {
        return toc;
    }

    /**
     * Sets the value of the toc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToc(String value) {
        this.toc = value;
    }

    public boolean isSetToc() {
        return (this.toc!= null);
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        if (status == null) {
            return "P";
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    public boolean isSetStatus() {
        return (this.status!= null);
    }

    /**
     * Gets the value of the trainCat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainCat() {
        if (trainCat == null) {
            return "OO";
        } else {
            return trainCat;
        }
    }

    /**
     * Sets the value of the trainCat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainCat(String value) {
        this.trainCat = value;
    }

    public boolean isSetTrainCat() {
        return (this.trainCat!= null);
    }

    /**
     * Gets the value of the isPassengerSvc property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getIsPassengerSvc() {
        if (isPassengerSvc == null) {
            return true;
        } else {
            return isPassengerSvc;
        }
    }

    /**
     * Sets the value of the isPassengerSvc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPassengerSvc(boolean value) {
        this.isPassengerSvc = value;
    }

    public boolean isSetIsPassengerSvc() {
        return (this.isPassengerSvc!= null);
    }

    public void unsetIsPassengerSvc() {
        this.isPassengerSvc = null;
    }

    /**
     * Gets the value of the deleted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getDeleted() {
        if (deleted == null) {
            return false;
        } else {
            return deleted;
        }
    }

    /**
     * Sets the value of the deleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeleted(boolean value) {
        this.deleted = value;
    }

    public boolean isSetDeleted() {
        return (this.deleted!= null);
    }

    public void unsetDeleted() {
        this.deleted = null;
    }

    /**
     * Gets the value of the isCharter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getIsCharter() {
        if (isCharter == null) {
            return false;
        } else {
            return isCharter;
        }
    }

    /**
     * Sets the value of the isCharter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCharter(boolean value) {
        this.isCharter = value;
    }

    public boolean isSetIsCharter() {
        return (this.isCharter!= null);
    }

    public void unsetIsCharter() {
        this.isCharter = null;
    }

    /**
     * Gets the value of the qtrain property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getQtrain() {
        if (qtrain == null) {
            return false;
        } else {
            return qtrain;
        }
    }

    /**
     * Sets the value of the qtrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setQtrain(boolean value) {
        this.qtrain = value;
    }

    public boolean isSetQtrain() {
        return (this.qtrain!= null);
    }

    public void unsetQtrain() {
        this.qtrain = null;
    }

    /**
     * Gets the value of the can property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getCan() {
        if (can == null) {
            return false;
        } else {
            return can;
        }
    }

    /**
     * Sets the value of the can property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCan(boolean value) {
        this.can = value;
    }

    public boolean isSetCan() {
        return (this.can!= null);
    }

    public void unsetCan() {
        this.can = null;
    }

}
