//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ppt.alarms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Type describing each type of alarm that can be set.
 * 
 * <p>Java class for RTTIAlarmData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTTIAlarmData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="tdAreaFail" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}TDAreaIDType"/>
 *         &lt;element name="tdFeedFail" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="tyrellFeedFail" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/Alarms/v1}AlarmID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTTIAlarmData", propOrder = {
    "tdAreaFail",
    "tdFeedFail",
    "tyrellFeedFail"
})
public class RTTIAlarmData {

    protected String tdAreaFail;
    protected Object tdFeedFail;
    protected Object tyrellFeedFail;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the tdAreaFail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdAreaFail() {
        return tdAreaFail;
    }

    /**
     * Sets the value of the tdAreaFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdAreaFail(String value) {
        this.tdAreaFail = value;
    }

    public boolean isSetTdAreaFail() {
        return (this.tdAreaFail!= null);
    }

    /**
     * Gets the value of the tdFeedFail property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTdFeedFail() {
        return tdFeedFail;
    }

    /**
     * Sets the value of the tdFeedFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTdFeedFail(Object value) {
        this.tdFeedFail = value;
    }

    public boolean isSetTdFeedFail() {
        return (this.tdFeedFail!= null);
    }

    /**
     * Gets the value of the tyrellFeedFail property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTyrellFeedFail() {
        return tyrellFeedFail;
    }

    /**
     * Sets the value of the tyrellFeedFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTyrellFeedFail(Object value) {
        this.tyrellFeedFail = value;
    }

    public boolean isSetTyrellFeedFail() {
        return (this.tyrellFeedFail!= null);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id!= null);
    }

}
