//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//
package uk.trainwatch.nre.darwin.model.ppt.stationmessages;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * <p>
 * <p>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "a")
public class A
        implements Serializable
{

    private static final long serialVersionUID = 1L;

    @XmlValue
    protected String value;
    @XmlAttribute(name = "href", required = true)
    protected String href;

    /**
     * Gets the value of the value property.
     * <p>
     * @return
     *         possible object is
     *         {@link String }
     * <p>
     */
    public String getValue()
    {
        return value;
    }

    /**
     * Sets the value of the value property.
     * <p>
     * @param value
     *              allowed object is
     *              {@link String }
     * <p>
     */
    public void setValue( String value )
    {
        this.value = value;
    }

    public boolean isSetValue()
    {
        return (this.value != null);
    }

    /**
     * Gets the value of the href property.
     * <p>
     * @return
     *         possible object is
     *         {@link String }
     * <p>
     */
    public String getHref()
    {
        return href;
    }

    /**
     * Sets the value of the href property.
     * <p>
     * @param value
     *              allowed object is
     *              {@link String }
     * <p>
     */
    public void setHref( String value )
    {
        this.href = value;
    }

    public boolean isSetHref()
    {
        return (this.href != null);
    }

}
