//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//


package uk.trainwatch.nre.darwin.model.ppt.stationmessages;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MsgCategoryType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MsgCategoryType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Train"/>
 *     &lt;enumeration value="Station"/>
 *     &lt;enumeration value="Connections"/>
 *     &lt;enumeration value="System"/>
 *     &lt;enumeration value="Misc"/>
 *     &lt;enumeration value="PriorTrains"/>
 *     &lt;enumeration value="PriorOther"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MsgCategoryType")
@XmlEnum
public enum MsgCategoryType {

    @XmlEnumValue("Train")
    TRAIN("Train"),
    @XmlEnumValue("Station")
    STATION("Station"),
    @XmlEnumValue("Connections")
    CONNECTIONS("Connections"),
    @XmlEnumValue("System")
    SYSTEM("System"),
    @XmlEnumValue("Misc")
    MISC("Misc"),
    @XmlEnumValue("PriorTrains")
    PRIOR_TRAINS("PriorTrains"),
    @XmlEnumValue("PriorOther")
    PRIOR_OTHER("PriorOther");
    private final String value;

    MsgCategoryType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MsgCategoryType fromValue(String v) {
        for (MsgCategoryType c: MsgCategoryType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
