//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 07:06:13 PM BST 
//
package uk.trainwatch.nre.darwin.model.ppt.stationmessages;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;

/**
 * Darwin Workstation Station Message
 * <p>
 * <p>
 * Java class for StationMessage complex type.
 * <p>
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <
 * pre>
 * &lt;complexType name="StationMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Station" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="crs" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}CrsType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Msg">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.thalesgroup.com/rtti/PushPort/StationMessages/v1}p" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{http://www.thalesgroup.com/rtti/PushPort/StationMessages/v1}a" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cat" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/StationMessages/v1}MsgCategoryType" />
 *       &lt;attribute name="sev" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/StationMessages/v1}MsgSeverityType" />
 *       &lt;attribute name="suppress" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * <p>
 * <p>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StationMessage", propOrder = {
    "station",
    "msg"
})
public class StationMessage
        implements Serializable
{

    private static final long serialVersionUID = 1L;

    @XmlElement(name = "Station")
    protected List<StationMessage.Station> station;
    @XmlElement(name = "Msg", required = true)
    protected StationMessage.Msg msg;
    @XmlAttribute(name = "id", required = true)
    protected int id;
    @XmlAttribute(name = "cat", required = true)
    protected MsgCategoryType cat;
    @XmlAttribute(name = "sev", required = true)
    protected String sev;
    @XmlAttribute(name = "suppress")
    protected Boolean suppress;

    /**
     * Gets the value of the station property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the station property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStation().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StationMessage.Station }
     * <p>
     * <p>
     */
    public List<StationMessage.Station> getStation()
    {
        if( station == null ) {
            station = new ArrayList<StationMessage.Station>();
        }
        return this.station;
    }

    public boolean isSetStation()
    {
        return ((this.station != null) && (!this.station.isEmpty()));
    }

    public void unsetStation()
    {
        this.station = null;
    }

    /**
     * Gets the value of the msg property.
     * <p>
     * @return
     *         possible object is
     *         {@link StationMessage.Msg }
     * <p>
     */
    public StationMessage.Msg getMsg()
    {
        return msg;
    }

    /**
     * Sets the value of the msg property.
     * <p>
     * @param value
     *              allowed object is
     *              {@link StationMessage.Msg }
     * <p>
     */
    public void setMsg( StationMessage.Msg value )
    {
        this.msg = value;
    }

    public boolean isSetMsg()
    {
        return (this.msg != null);
    }

    /**
     * Gets the value of the id property.
     * <p>
     */
    public int getId()
    {
        return id;
    }

    /**
     * Sets the value of the id property.
     * <p>
     */
    public void setId( int value )
    {
        this.id = value;
    }

    public boolean isSetId()
    {
        return true;
    }

    /**
     * Gets the value of the cat property.
     * <p>
     * @return
     *         possible object is
     *         {@link MsgCategoryType }
     * <p>
     */
    public MsgCategoryType getCat()
    {
        return cat;
    }

    /**
     * Sets the value of the cat property.
     * <p>
     * @param value
     *              allowed object is
     *              {@link MsgCategoryType }
     * <p>
     */
    public void setCat( MsgCategoryType value )
    {
        this.cat = value;
    }

    public boolean isSetCat()
    {
        return (this.cat != null);
    }

    /**
     * Gets the value of the sev property.
     * <p>
     * @return
     *         possible object is
     *         {@link String }
     * <p>
     */
    public String getSev()
    {
        return sev;
    }

    /**
     * Sets the value of the sev property.
     * <p>
     * @param value
     *              allowed object is
     *              {@link String }
     * <p>
     */
    public void setSev( String value )
    {
        this.sev = value;
    }

    public boolean isSetSev()
    {
        return (this.sev != null);
    }

    /**
     * Gets the value of the suppress property.
     * <p>
     * @return
     *         possible object is
     *         {@link Boolean }
     * <p>
     */
    public boolean getSuppress()
    {
        if( suppress == null ) {
            return false;
        }
        else {
            return suppress;
        }
    }

    /**
     * Sets the value of the suppress property.
     * <p>
     * @param value
     *              allowed object is
     *              {@link Boolean }
     * <p>
     */
    public void setSuppress( boolean value )
    {
        this.suppress = value;
    }

    public boolean isSetSuppress()
    {
        return (this.suppress != null);
    }

    public void unsetSuppress()
    {
        this.suppress = null;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <
     * pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.thalesgroup.com/rtti/PushPort/StationMessages/v1}p" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.thalesgroup.com/rtti/PushPort/StationMessages/v1}a" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * <p>
     * <p>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Msg
            implements Serializable
    {

        private static final long serialVersionUID = 1L;

        @XmlElementRefs({
            @XmlElementRef(name = "a", namespace = "http://www.thalesgroup.com/rtti/PushPort/StationMessages/v1", type = A.class, required = false),
            @XmlElementRef(name = "p", namespace = "http://www.thalesgroup.com/rtti/PushPort/StationMessages/v1", type = P.class, required = false)
        })
        @XmlMixed
        protected List<Object> content;

        /**
         * Gets the value of the content property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link A }
         * {@link P }
         * {@link String }
         * <p>
         * <p>
         */
        public List<Object> getContent()
        {
            if( content == null ) {
                content = new ArrayList<Object>();
            }
            return this.content;
        }

        public boolean isSetContent()
        {
            return ((this.content != null) && (!this.content.isEmpty()));
        }

        public void unsetContent()
        {
            this.content = null;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <
     * pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="crs" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}CrsType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * <p>
     * <p>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Station
            implements Serializable
    {

        private static final long serialVersionUID = 1L;

        @XmlAttribute(name = "crs", required = true)
        protected String crs;

        /**
         * Gets the value of the crs property.
         * <p>
         * @return
         *         possible object is
         *         {@link String }
         * <p>
         */
        public String getCrs()
        {
            return crs;
        }

        /**
         * Sets the value of the crs property.
         * <p>
         * @param value
         *              allowed object is
         *              {@link String }
         * <p>
         */
        public void setCrs( String value )
        {
            this.crs = value;
        }

        public boolean isSetCrs()
        {
            return (this.crs != null);
        }

    }

}
