var Ref = (function () {
    function Ref() {

        Ref.cancCode = {};
        Ref.cancDesc = {};
        
        $.each([
            //["Code","Cause","Abbreviation"],
            ["AA", "Waiting Terminal/Yard acceptance", "ACCEPTANCE"],
            ["AB", "Waiting Customer release of documentation", "DOCUMENTS"],
            ["AC", "Waiting train preparation or completion of TOPS list/RT3973", "TRAIN PREP"],
            ["AD", "Terminal/Yard staff shortage including reactionary congestion caused by the shortage", "WTG STAFF"],
            ["AE", "Congestion in Terminal/Yard", "CONGESTION"],
            ["AF", "Terminal/Yard equipment failure - cranes etc", "EQUIPMENT"],
            ["AG", "Adjusting Loaded wagons", "LOAD INCDT"],
            ["AH", "Customer equipment breakdown/reduced capacity", "BREAKDOWN"],
            ["AJ", "Waiting Customer's traffic including ship/road/air connections and Mail deliveries.", "TRAFFIC"],
            ["AK", "Fire in freight yard / terminal (including private sidings, and stations Ð where it affects FOC services)", "INF FIRE"],
            ["AX", "Failure of FOC-owned infrastructure", "FOC INFRA"],
            ["AY", "Mishap in Terminal/Yard or on Terminal/Yard infrastructure", "FTO MISHAP"],
            ["AZ", "Other Freight Operating Company, cause to be specified", "FTO OTHER"],
            ["FA", "Dangerous goods incident", "DGI INCDT"],
            ["FB", "Train stopped on route due to incorrect marshalling", "REMARSHALL"],
            ["FC", "Freight train driver", "FCDRIVER"],
            ["FD", "Booked loco used on additional/other service", "LOCO USED"],
            ["FE", "Traincrew rostering error/not available, including crew relief errors", "NO T/CREW"],
            ["FG", "Driver adhering to company professional driving standards or policy", "PRO DVR"],
            ["FH", "Train crew/loco diagram/planning error (See also DAG Section 4.31.2)", "DIAG ERROR"],
            ["FI", "Delay in running due to the incorrect operation of the on- board ETCS/ ERTMS equipment Ð i.e. wrong input by driver.", "ETCS INPUT"],
            ["FJ", "Train held at Customer's request", "RETIME REQ"],
            ["FK", "Train diverted/re-routed at Customer's request", "DIVERT REQ"],
            ["FL", "Train cancelled at Customer's request", "CANCEL REQ"],
            ["FM", "Tail lamp/head lamp out or incorrectly shown", "TAIL LAMP"],
            ["FN", "Late presentation from Europe", "LATE CHUNL"],
            ["FO", "Delay in running believed to be due to Operator, but no information available from that Operator", "FOC UNEX"],
            ["FP", "Incorrect route taken or route wrongly challenged by driver, including SPADÕs", "FTO MISRTE"],
            ["FS", "Delay due to ETCS/ ERTMS on-board overriding driver command", "ETCS OVRD"],
            ["FT", "Freight Operator autumn-attribution Neutral Zone delays", "LF NEUTRAL"],
            ["FU", "Formal Inquiry Incident - possible Operator responsibility", "JOINT INQ"],
            ["FW", "Late start/yard overtime not explained by Operator", "LATE START"],
            ["FX", "Freight train running at lower than planned classification", "LOW CLASS"],
            ["FY", "Mishap caused by Freight Operating Company or on FOC-owned infrastructure", "FOC MISHAP"],
            ["FZ", "Other Freight Operating Company causes, including Freight Operating Company Control directive, cause to be specified", "FOC OTHER"],
            ["I0", "Telecom equipment failures legacy (inc. NRN/CSR/RETB link)", "RADIO FLR"],
            ["I1", "Overhead line/third rail defect", "OHL/3 RAIL"],
            ["I2", "AC/DC trip", "AC/DC TRIP"],
            ["I3", "Obstruction on OHL, cause of which is not known", "ON OHL"],
            ["I4", "OHL/third rail power supply failure/reduction", "SUPPLY FLR"],
            ["I5", "Possession over-run from planned work", "OVERRUN"],
            ["I6", "Track Patrolling", "TRK PATROL"],
            ["I7", "Engineer's train late/failed in possession", "ENGNRS TRN"],
            ["I8", "Animal Strike/Incursion within the control of Network Rail", "ANIMAL"],
            ["I9", "Fires starting on Network Rail Infrastructure", "NR FIRE"],
            ["IA", "Signal failure", "SIGNAL FLR"],
            ["IB", "Points failure", "POINTS FLR"],
            ["IC", "Track circuit failure", "TC FAILURE"],
            ["ID", "Level crossing failure incl. barrow/foot crossings and crossing treadles", "LEVEL XING"],
            ["IE", "Power failure", "POWER FLR"],
            ["IF", "Train Describer/Panel/ARS/SSI/TDM/Remote Control failure", "PANEL/TDM/FLR"],
            ["IG", "Block failure", "BLOCK FLR"],
            ["II", "Power Supply cable fault/fire due to cable fault", "CABLE FLR"],
            ["IJ", "AWS/ATP/TPWS/Train Stop/On-track equipment failure", "AWS/ATP"],
            ["IK", "Telephone equipment failure", "PHONE/SPT"],
            ["IL", "Token equipment failure", "TOKEN FLR"],
            ["IM", "Infrastructure Balise Failure", "BALISE"],
            ["IN", "HABD/Panchex/WILD/Wheelchex", "HABD FAULT"],
            ["IO", "No fault found/HABD/Panchex/WILD/Wheelchex", "NFF"],
            ["IP", "Points failure caused by snow or frost where heaters are fitted but found to be not operative or defective", "PNT HEATER"],
            ["IQ", "Trackside sign blown down/light out etc", "TRACK SIGN"],
            ["IR", "Broken/cracked/twisted/buckled/flawed rail", "RAIL FLAW"],
            ["IS", "Track defects (other than rail defects i.e. fish plates, wet beds etc)", "TRACK FLT"],
            ["IT", "Bumps reported - cause not known", "BUMP RPRTD"],
            ["IU", "Engineers on-track plant affecting possession", "ONTRACK EQ"],
            ["IV", "Earthslip/subsidence/breached sea defences not the result of severe weather", "EARTHSLIP"],
            ["IW", "Non severe- Snow/Ice/Frost affecting infrastructure equipment", "COLD"],
            ["IY", "Mishap - Network Rail causes", "INF MISHAP"],
            ["IZ", "Other infrastructure causes", "INF OTHER"],
            ["J0", "Telecom radio failures IVRS/GSM-R", "GSM-R FLR"],
            ["J2", "TRTS Failure", "TRTS FLR"],
            ["J3", "Axle Counter Failure", "AXLE FLR"],
            ["J4", "Safety Issue No Fault Found", "INF NFF"],
            ["J5", "NR DOO monitor/mirror failure", "DOO MON FLR"],
            ["J6", "Lightning strike against unprotected assets", "LIGHTNING"],
            ["J7", "ETCS/ ERTMS Equipment Failure (excluding communications link and balises)", "ETCS FLR"],
            ["J8", "Damage to infrastructure caused by on-track machine whilst operating in a possession", "ONTRK DMG"],
            ["JA", "TSR speeds for Track-work outside the Rules of the Route", "TSR O-ROTR"],
            ["JB", "Reactionary Delay to 'P' coded TSR", "PLND TSR"],
            ["JC", "Telecom cable failure (transmission sys & cable failures )", "COMM LINKS"],
            ["JD", "Bridges/tunnels/buildings (other than bridge strikes)", "STRUCTURES"],
            ["JG", "ESR/TSR due to cancelled possession/work not completed", "ESR/TSR"],
            ["JH", "Critical Rail Temperature speeds, (other than buckled rails)", "HEAT SPEED"],
            ["JI", "Swing/lifting bridge failure", "SWING BDGE"],
            ["JK", "Flooding not due to exceptional weather", "FLOODING"],
            ["JL", "Network Rail/TRC Staff error", "STAFF"],
            ["JM", "Change of Signal Aspects - no fault found", "ASPECT CHG"],
            ["JN", "Possession cancellation", "POSSN CANC"],
            ["JO", "Rolling Contact Fatigue", "RCF"],
            ["JP", "Failure to maintain vegetation within network boundaries in accordance with prevailing Network Rail standards", "VEG STD"],
            ["JQ", "Trains striking overhanging branches/vegetation (not weather- related)", "TREE OHANG"],
            ["JR", "Signals/track signs obscured by vegetation", "HIDDEN SIG"],
            ["JS", "Condition of Track TSR Outside Rules of Route", "COTTSR ORR"],
            ["JT", "Points failure caused by snow or frost where heaters are not fitted", "NO PNT HTR"],
            ["JX", "Miscellaneous items (including trees) causing obstructions, not the result of trespass, vandalism, weather or fallen/thrown from trains", "MISC OBS"],
            ["M0", "Safety systems failure (DSD/OTMR/Vigilance)", "DSD"],
            ["M1", "Pantograph fault or PANCHEX activation (positive)", "PANTOGRAPH"],
            ["M2", "Automatic Dropper Device activation", "ADD"],
            ["M3", "Diesel loco failure/defect/attention: other", "DIESL OTH"],
            ["M4", "EMU failure/defect/attention: brakes", "EMU BRAKE"],
            ["M5", "EMU failure/defect/attention: doors (including SDO equipment failure)", "EMU DOOR"],
            ["M6", "EMU failure/defect/attention: other", "EMU OTHER"],
            ["M7", "DMU (inc. HST/MPV) failure/defect/attention: doors (including SDO equipment failure and excluding Railhead Conditioning trains).", "DMU DOOR"],
            ["M8", "DMU (inc. HST/MPV) failure/defect/attention: other (excluding Railhead Conditioning trains)", "DMU OTHER"],
            ["M9", "Reported fleet equipment defect - no fault found", "NFF"],
            ["MA", "Electric loco (inc. IC225) failure/defect/attention: brakes", "ELEC BRAKE"],
            ["MB", "Electric loco (inc. IC225) failure/defect/attention: traction", "ELEC TRAC"],
            ["MC", "Diesel loco failure/defect/attention: traction", "DIESL TRAC"],
            ["MD", "DMU (inc. HST)/MPV failure/defect/attention: traction (excluding Railhead Conditioning trains)", "DMU TRAC"],
            ["ME", "Steam locomotive failure/defect/attention", "STEAM LOCO"],
            ["MF", "International/Channel Tunnel locomotive failure/defect/attention", "CHUNL LOCO"],
            ["MG", "Coach (inc. Intl/IC225) failure/defect/attention: brakes", "COACH BRKE"],
            ["MH", "Coach (inc. Intl/IC225) failure/defect/attention: doors", "COACH DOOR"],
            ["MI", "Coach (inc. Intl/IC225) failure/defect/attention: other", "COACH OTHR"],
            ["MJ", "Parcels vehicle failure/defect/attention", "PARCEL VEH"],
            ["MK", "DVT/PCV failure/defect/attention", "DVT PCV"],
            ["ML", "Freight vehicle failure/defect attention (inc. private wagons)", "FRGHT VEH"],
            ["MM", "EMU failure/defect/attention: traction", "EMU TRAC"],
            ["MN", "DMU (inc. HST/MPV) failure/defect/attention: brakes (excluding Railhead Conditioning trains)", "DMU BRAKE"],
            ["MO", "Loco/unit/vehicles late off depot (cause not known)", "STOCK LATE"],
            ["MP", "Loco/unit adhesion problems", "ADHESION"],
            ["MQ", "Electric loco (inc. IC225) failure/defect/attention: other", "ELEC OTHER"],
            ["MR", "Hot Box or HABD/WILD activation (positive)", "HOT BOX"],
            ["MS", "Stock change or replacement by slower vehicles (all vehicle types)", "STOCK CHNG"],
            ["MT", "Safety systems failure (AWS/TPWS/ATP)", "AWS TPWS"],
            ["MU", "Depot operating problem", "DEPOT"],
            ["MV", "EngineerÕs on-track equipment failure outside possession", "ON-TRACK"],
            ["MW", "Weather Ð effect on T&RS equipment", "WEATHER"],
            ["MX", "Diesel loco failure/defect/attention: brakes", "DIESL BRKE"],
            ["MY", "Mishap Ð T&RS cause", "TRS MISHAP"],
            ["MZ", "Other Fleet Engineer causes/initial attribution", "T+RS OTHER"],
            ["NA", "Ontrain TASS Failure", "TASS"],
            ["NB", "TASS Ð No fault found", "TASS NFF"],
            ["NC", "Fire in fleet depot not caused by vandals (includes caused by vandals in respect of freight depots)", "DEP FIRE"],
            ["ND", "On train ETCS/ ERTMS failure", "ETCS"],
            ["O2", "ACI Failures", "ACI FAIL"],
            ["OB", "Delayed by signaller not applying applicable regulating policy", "Regulation"],
            ["OC", "Signaller, including wrong routing and wrong ETCS/ ERTMS instruction", "SIGNALLER"],
            ["OD", "Delayed as a result of Route Control directive", "NR CONTROL"],
            ["OE", "Failure to lay Sandite or operate Railhead Conditioning train as programmed", "RHC PROG"],
            ["OG", "Ice on conductor rail/OLE", "ICE"],
            ["OH", "ARS software problem (excluding scheduling error and technical failures)", "ARS"],
            ["OI", "Formal Inquiry Incident - other operators", "JOINT INQ"],
            ["OJ", "Fire in station building or on platform, affecting operators not booked to call at that station", "STN FIRE"],
            ["OK", "Delay caused by Operating staff oversight, error or absence (excluding signallers and Control)", "OPTG STAFF"],
            ["OL", "Signal Box not open during booked hours", "BOX CLOSED"],
            ["OM", "Technical failure associated with a Railhead Conditioning train", "RHC FLR"],
            ["ON", "Delays not properly investigated by Network Rail", "Mis-invest"],
            ["OO", "Late start of a RHC", "RHC"],
            ["OP", "Failure of TRUST/SMART systems", "TRUST FLR"],
            ["OQ", "Incorrect Simplifier", "SIMP ERR"],
            ["OS", "Delays to other trains caused by a Railhead Conditioning train taking unusually long time in section or at a location", "RHC LATE"],
            ["OU", "Delays un-investigated", "Un-invest"],
            ["OV", "Fire or evacuation due to fire alarm of Network Rail buildings other than stations not due to vandalism", "NR FIRE"],
            ["OW", "Connections held where the prime incident causing delay to the incoming train is a FOC owned incident and service is more frequent than hourly", "FOC CONN"],
            ["OY", "Mishap - Network Rail Operating cause", "NR MISHAP"],
            ["OZ", "Other Network Rail Operating causes", "OPTG OTHER"],
            ["PA", "Trackwork TSR within Rules of the Route", "PLANND TSR"],
            ["PB", "Condition of Track TSR within Rules of the Route", "PLANND COT"],
            ["PC", "Condition of Bridge TSR within rules of the route", "PLANND COB"],
            ["PD", "TPS cancellation (Not to be input in TSI/TRUST)", "TPS CANC"],
            ["PE", "Cancelled due to planned engineering work", "ENGNRG WRK"],
            ["PF", "Planned engineering work - diversion/SLW not timetabled (within Rules of the Route)", "DIVRSN/SLW"],
            ["PG", "Planned cancellation by Train Operator", "PLAND CANC"],
            ["PH", "Condition of Earthworks TSR within Rules of the Route", "PLND COE"],
            ["PI", "TSR for Schedule 4 Possession", "SCH 4 TSR"],
            ["PJ", "Duplicate delay", "DUPLICATE"],
            ["PK", "Bank Holiday Cancellation", "BANK HOL"],
            ["PL", "Exclusion agreed between Network Rail and Train Operator", "AGREED EXC"],
            ["PN", "Minor delays to VSTP service caused by regulation / time lost in running.", "VSTP DELAY"],
            ["PS", "Cancellation of a duplicate or erroneous schedule", "DUPE SCHLD"],
            ["PT", "TRUST Berth Offset Errors", "OFFSET ERR"],
            ["PZ", "Other contractual exclusion", "OTH EXC"],
            ["QA", "WTT Schedule / LTP process", "WTT SCHED"],
            ["QB", "Planned engineering work - diversion/SLW not timetabled (outside rules of the route)", "DIVRSN/SLW"],
            ["QH", "Adhesion problems due to leaf contamination", "LEAF SLIP"],
            ["QI", "Cautioning due to railhead leaf contamination", "RLHD CONT"],
            ["QJ", "Special working for leaf-fall track circuit operation", "LEAVES T/C"],
            ["QM", "STP schedule / STP process", "STP SCHED"],
            ["QN", "VSTP schedule / VSTP process (TSI created schedule)", "TSI SCHED"],
            ["QP", "Reactionary Delay to ÒPÓ coded Possession", "PLND LOP"],
            ["QQ", "Simplifier Error Ops Planning", "OPS S ERR"],
            ["QT", "Delay accepted by Network Rail as part of a commercial agreement where no substantive delay reason is identified", "TAKEBACK"],
            ["QZ", "Other Network Rail non-Operating causes", "COMM OTHER"],
            ["R1", "Incorrect train dispatch by station staff", "DISPATCH"],
            ["R2", "Late TRTS given by station staff", "LATE TRTS"],
            ["R3", "Station staff unavailable - missing or uncovered", "STAFF MSN"],
            ["R4", "Station staff split responsibility - unable to cover all duties", "STAFF DUTY"],
            ["R5", "Station staff error - e.g. wrong announcements, misdirection", "STAFF ERR"],
            ["R6", "Overtime at stations normally unstaffed.", "UNSTAFFED"],
            ["R7", "Station delays due to special events e.g. sports fixtures", "SPORTS"],
            ["RB", "Passengers joining/alighting", "PASSENGERS"],
            ["RC", "Assisting a disabled person joining/alighting, pre-booked", "DISAB 1"],
            ["RD", "Attaching/detaching/shunter/watering", "ATT/DETACH"],
            ["RE", "Lift/escalator defect/failure", "LIFT/ESC"],
            ["RF", "Loading/unloading letter mails/parcels", "MAIL/PRCLS"],
            ["RH", "Station evacuated due to fire alarm", "FIRE ALARM"],
            ["RI", "Waiting connections - not authorised by TOC Control", "UNAUTH CON"],
            ["RJ", "Special Stop Orders - not authorised by TOC Control", "UNAUTH SSO"],
            ["RK", "Waiting connections - authorised by TOC Control", "AUTH CON"],
            ["RL", "Special Stop Orders - authorised by TOC Control", "AUTH SSO"],
            ["RM", "Waiting connections from other transport modes", "XTNL CONN"],
            ["RN", "Passengers ÒforcingÓ connections between trains outside connectional allowances", "PASS CONN"],
            ["RO", "Passengers taken ill on platform", "PASS ILL"],
            ["RP", "Passengers dropping items on track (not vandalism)", "PASS DROP"],
            ["RQ", "Assisting a disabled person joining/alighting, unbooked", "DISAB 2"],
            ["RR", "Loading reserved bicycles presented late", "BIKE 1"],
            ["RS", "Loading unreserved bicycles", "BIKE 2"],
            ["RT", "Loading excessive luggage", "LUGGAGE 1"],
            ["RU", "Locating lost luggage", "LUGGAGE 2"],
            ["RV", "Customer Information System failure", "PASS INFO"],
            ["RW", "Station flooding (including issues with drains) not the result of weather, where the water has not emanated from Network Rail maintained infrastructure/network", "STN FLOOD"],
            ["RY", "Mishap - Station Operator cause", "STN MISHAP"],
            ["RZ", "Other Station Operator causes", "STN OTHER"],
            ["T1", "Delay at unstaffed station to DOO train", "DOO STN"],
            ["T2", "Delay at unstaffed station to non-DOO train", "NONDOO STN"],
            ["T3", "Waiting connections from other transport modes", "XTNL CONN"],
            ["T4", "Loading Supplies (including catering)", "SUPPLIES"],
            ["TA", "Traincrew/loco/stock/unit diagram error (See also DAG Section 4.31.2)", "DIAG ERROR"],
            ["TB", "Train cancelled/delayed at Train OperatorÕs request", "TOC REQST"],
            ["TC", "Booked Traincrew used for additional/other service", "CREW USED"],
            ["TD", "Booked loco/stock/unit used for additional/other service", "STOCK USED"],
            ["TE", "Injury to passenger on train", "PASS INJRY"],
            ["TF", "Seat reservation problems", "SEAT RESVN"],
            ["TG", "Driver", "DRIVER"],
            ["TH", "(Senior) Conductor/Train Manager", "(SNR) COND"],
            ["TI", "Traincrew rostering problem", "ROSTERING"],
            ["TJ", "Tail lamp/headlamp out", "TAIL LAMP"],
            ["TK", "Train catering staff (including Contractors)", "CATERING"],
            ["TL", "Door open / not properly secured incident", "DOOR OPEN"],
            ["TM", "Connection authorised by TOC but outwith connection policy", "AUTH CONN"],
            ["TN", "Late presentation from the continent", "LATE CHUNL"],
            ["TO", "Delay believed to be due to Operator, but no information available from Operator", "TOC UNEX"],
            ["TP", "Special Stop Orders", "AUTH SSO"],
            ["TR", "Train Operating Company Directive", "TOC DIRECT"],
            ["TS", "Delay due to ETCS/ ERTMS on-board overriding driver command", "ETCS OVRD"],
            ["TT", "Autumn-attribution Neutral Zone delays (See Supplementary Autumn Attribution Guidance)", "LF NEUTRAL"],
            ["TU", "Formal Inquiry Incident - possible Operator responsibility", "JOINT INQ"],
            ["TW", "Driver adhering to company professional driving standards or policy", "PRO DVR"],
            ["TX", "Delays incurred on non-Network Rail running lines including London Underground causes (except T&RS)", "LUL CAUSES"],
            ["TY", "Mishap-Train Operating Company cause", "TOC MISHAP"],
            ["TZ", "Other Passenger Train Operating Company causes", "TOC OTHER"],
            ["V8", "Train striking other birds", "OTH BIRDS"],
            ["VA", "Disorder/drunks/trespass etc", "DISORDER"],
            ["VB", "Vandalism/theft", "VANDALS"],
            ["VC", "Fatalities/injuries sustained whilst on a platform as the result of being struck by a train or falling from a train", "FATALITIES"],
            ["VD", "Passenger taken ill on train", "ILL PASS"],
            ["VE", "Ticket irregularities/refusals to pay", "TICKET IRR"],
            ["VF", "Fire caused by vandalism", "VDL FIRE"],
            ["VG", "Police searching train", "POLICE-TRN"],
            ["VH", "Communication cord/emergency train alarm operated", "COM CORD"],
            ["VI", "Security alert affecting stations and depots", "SEC ALERT"],
            ["VR", "Driver adhering to company professional driving standards or policies during severe weather conditions that are not fleet related", "PRO DVR"],
            ["VW", "Severe weather affecting passenger fleet equipment including following company standards/policies or Rule Book instructions", "WEATHER"],
            ["VX", "Passenger charter excludable events occurring on the LUL or other non NR running lines", "LUL CAUSES"],
            ["VZ", "Other passenger/external causes the responsibility of TOC", "EXT OTHER"],
            ["X1", "Visibility in semaphore signalled areas, or special working for fog and falling snow implemented by Network Rail Ð in all signalling areas", "SPL REGS"],
            ["X2", "Severe flooding beyond that which could be mitigated on Network Rail infrastructure", "SEV FLOOD"],
            ["X3", "Lightning Strike Ð damage to protected systems.", "LGHTNG"],
            ["X4", "Blanket speed restriction for extreme heat or high wind in accordance with the Group Standards", "BLNK REST"],
            ["X8", "Animal Strike/Incursion not within the control of Network Rail", "EXT ANIMAL"],
            ["X9", "Points failure caused by severe snow where heaters are working as designed", "SEV SNOW"],
            ["XA", "Trespass", "TRESPASS"],
            ["XB", "Vandalism/theft (including the placing of objects on the line)", "VANDALS"],
            ["XC", "Fatalities/ injuries caused by being hit by train", "FATALITIES"],
            ["XD", "Level Crossing Incidents", "XING INCDT"],
            ["XF", "Police searching line", "POLICE-RLY"],
            ["XH", "Severe heat affecting infrastructure the responsibility of Network Rail (excluding Heat speeds)", "SEV HEAT"],
            ["XI", "Security alert affecting Network Rail Network", "SEC ALERT"],
            ["XK", "External Power Supply Failure Network Rail Infrastructure", "EXTL POWER"],
            ["XL", "Fire external to railway infrastructure", "EXTL FIRES"],
            ["XM", "Gas/water mains/overhead power lines", "GAS/WATER"],
            ["XN", "Road related - excl bridge strikes/level crossing incident", "ROAD INCDT"],
            ["XO", "External trees, building or objects encroaching onto Network Rail infrastructure (not due to weather or vandalism)", "EXT OBJECT"],
            ["XP", "Bridge Strike", "BDG STRIKE"],
            ["XQ", "Swing bridge open for river or canal traffic", "BDGE OPEN"],
            ["XR", "Cable vandalism/theft", "CABLE CUT"],
            ["XS", "Level Crossing misuse", "XNG MISUSE"],
            ["XT", "Severe cold weather affecting infrastructure the responsibility of Network Rail", "SEV COLD"],
            ["XU", "Sunlight on signal", "SUN OBSCUR"],
            ["XV", "Fire or evacuation due to fire alarm of Network Rail buildings other than stations due to vandalism", "NR FIRE"],
            ["XW", "High winds affecting infrastructure the responsibility of Network Rail including objects on the line due to the effect of weather", "WIND"],
            ["XZ", "Other external causes the responsibility of Network Rail", "EXT OTHER"],
            ["YA", "Lost path - regulated for train running on time", "REG-ONTIME"],
            ["YB", "Lost path - regulated for another late running train", "REG-LATE"],
            ["YC", "Lost path - following train running on time", "FOL-ONTIME"],
            ["YD", "Lost path - following another late running train", "FOL-LATE"],
            ["YE", "Lost path - waiting acceptance to single line", "TO S/LINE"],
            ["YF", "Waiting for late running train off single line", "OFF SLINE"],
            ["YG", "Regulated in accordance with Regulation Policy", "CORRCT REG"],
            ["YH", "Late arrival of inward loco", "INWD LOCO"],
            ["YI", "Late arrival of inward stock/unit", "INWD STOCK"],
            ["YJ", "Late arrival of Traincrew on inward working", "INWD CREW"],
            ["YK", "Waiting connecting Freight or Res traffic to attach", "CNNCTN TFC"],
            ["YL", "Waiting passenger connections within Connection Policy", "AUTHSD CON"],
            ["YM", "Special stop orders agreed by Control", "AUTHSD SSO"],
            ["YN", "Booked traincrew not available for late running train", "FIND CREW"],
            ["YO", "Waiting platform/station congestion/platform change", "PLATFORM"],
            ["YP", "Delayed by diverted train", "DIVERSION"],
            ["YQ", "Passenger overcrowding caused by a train being of short- formation", "SHRT FRMD"],
            ["YU", "Prime cause of most unit swaps", "UNIT SWAPS"],
            ["YX", "Passenger overcrowding caused by delay/cancellation of another train", "OVER CRWD"],
            ["ZW", "Unattributed Cancellations", "UNATR CAN"],
            ["ZX", "Unexplained late start", "UNEX L/S"],
            ["ZY", "Unexplained Station overtime", "UNEX O/T"],
            ["ZZ", "Unexplained loss in running", "UNEX L/R"]
        ],
                function (i, e) {
                    Ref.cancCode[e[0]] = e[2];
                    Ref.cancDesc[e[0]] = e[1];
                });
    }
    return Ref;
})();
new Ref();
